name: build and push container image
on:
  workflow_dispatch:

jobs:
  build_and_push:
    name: build and push container image
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login --username $GITHUB_ACTOR --password-stdin ghcr.io

      - name: build
        run: docker build --tag ghcr.io/mtakahashiif/sample:latest .

      - name: push
        run: docker push ghcr.io/mtakahashiif/sample:latest
